variables:
  PROJECT_NAME: @PROJECT_NAME@

workflow:
  rules:
    - if: '$CI_PIPELINE_SOURCE == "merge_request_event"'
      when: never
    - if: '$CI_COMMIT_REF_NAME == "develop"'
      when: always
      variables:
        ENVIRONMENT_URL: @APP URL@
        TARGET_HOST: docker-server-1
        TARGET_POSTGRES_HOST: db-server-1
    - when: never

include:
  - project: 'webcentriq-next/felixin'
    ref: latest
    file: '/ci/backend/with-docker.gitlab-ci.yml'
  - project: 'webcentriq-next/felixin'
    ref: latest
    file: '/ci/db/postgres.gitlab-ci.yml'
