version: '3'

services:
  web:
    build: .
    command: bash runserver.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .envs/local/.django

  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    env_file:
      - .envs/local/.postgres
    ports:
      - "5432:5432"
