version: '3.9'

services:
  backend:
    build:
      context: ./
      dockerfile: ./Dockerfile.prod
    restart: unless-stopped
    container_name: starter_backend_prod
    hostname: starter_backend_prod
    ports:
      - "8000:8000"
    env_file:
      - ./.envs/.django
    depends_on:
      database:
        condition: service_healthy
      redis:
        condition: service_healthy
    entrypoint: "/app/scripts/entrypoint.sh"
    volumes:
      - ../static:/app/static
      - ../media:/app/media
      - ./apps:/app/apps
    healthcheck:
      test: ["CMD", "/app/scripts/health.sh"]
      interval: 10s
      retries: 8
      start_period: 5s
      timeout: 5s

  database:
    image: postgres:14
    restart: unless-stopped
    container_name: starter_database_prod
    hostname: starter_database_prod
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    env_file:
      - ../.envs/.postgres
    expose:
      - 5432
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 3s
      retries: 10
      start_period: 5s
      timeout: 3s

  redis:
    image: redis:7
    restart: unless-stopped
    container_name: starter_redis_prod
    hostname: starter_redis_prod
    env_file:
      - ./.envs/.redis
    expose:
      - 6379
    volumes:
      - ./redis_data:/bitnami/redis/data
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 3s
      retries: 10
      start_period: 5s
      timeout: 3s
